// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABjdlpWz8JFmbXehXwjHMZaSbB39dRLpM',
    appId: '1:983597005932:web:e3d38d7d2fb8ea3c052c49',
    messagingSenderId: '983597005932',
    projectId: 'auth-employe',
    authDomain: 'auth-employe.firebaseapp.com',
    storageBucket: 'auth-employe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNlH2_Xk3vfSHPff6_Tt5fbJ6tLduGecU',
    appId: '1:983597005932:android:d43c4321945cb6a1052c49',
    messagingSenderId: '983597005932',
    projectId: 'auth-employe',
    storageBucket: 'auth-employe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdars6KFLHWgRFG8oGgEHcG1Z5wK0uQHA',
    appId: '1:983597005932:ios:faec191d22d59bde052c49',
    messagingSenderId: '983597005932',
    projectId: 'auth-employe',
    storageBucket: 'auth-employe.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdars6KFLHWgRFG8oGgEHcG1Z5wK0uQHA',
    appId: '1:983597005932:ios:afcbb0f6a78074d8052c49',
    messagingSenderId: '983597005932',
    projectId: 'auth-employe',
    storageBucket: 'auth-employe.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo.RunnerTests',
  );
}
